import "dotenv/config";
import { faker } from "@faker-js/faker";
import { drizzle } from "drizzle-orm/node-postgres";
import { Pool } from "pg";
import {
  type diffLineTypeEnum,
  type issueSeverityEnum,
  roastDiffs,
  roastIssues,
  submissions,
  type verdictEnum,
} from "./schema";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

type Verdict = (typeof verdictEnum.enumValues)[number];
type Severity = (typeof issueSeverityEnum.enumValues)[number];
type DiffLineType = (typeof diffLineTypeEnum.enumValues)[number];

// ---------------------------------------------------------------------------
// Static pools — deterministic, realistic content
// ---------------------------------------------------------------------------

const LANGUAGES = [
  "javascript",
  "typescript",
  "python",
  "php",
  "java",
  "ruby",
  "go",
  "csharp",
  "sql",
  "bash",
];

const ROAST_QUOTES: string[] = [
  "this code was written during a power outage... in 2005.",
  "i've seen better structure in a bowl of spaghetti.",
  "somewhere, a computer science professor is crying and doesn't know why.",
  "this is what happens when you learn to code from a fortune cookie.",
  "i've seen more thoughtful code written by a cat walking on a keyboard.",
  "calling this 'working code' is the most generous interpretation of both words.",
  "this would fail a code review at a company that hasn't invented code reviews yet.",
  "whoever wrote this clearly peaked at hello world.",
  "the real bug is that this was ever committed to version control.",
  "this code has more issues than a magazine subscription service.",
  "i'm not saying it's wrong, i'm saying it's aggressively incorrect.",
  "this is the coding equivalent of a participation trophy.",
  "your variable names are a hate crime against future maintainers.",
  "this passes the tests because the tests are also broken.",
  "the only thing consistent here is the inconsistency.",
  "this code is on a first-name basis with undefined behavior.",
  "if copy-paste was a crime, you'd have three life sentences.",
  "there are more globals here than in a geography final.",
  "this would make a great interview question — what not to do.",
  "the indentation alone is grounds for immediate termination.",
  "god saw this code and invented compiler errors.",
  "this file has more todos than a monday morning to-do list.",
  "whoever named these functions has never met a verb before.",
  "the nesting level here could cause vertigo.",
  "this function does six things and none of them well.",
  "i've seen cleaner code in a ransomware sample.",
  "this is what happens when you google the solution but not the problem.",
  "the error handling strategy here is 'hope for the best'.",
  "this entire file is a race condition waiting to happen.",
  "magic numbers everywhere — this reads like a phone book.",
  "null checks? never heard of them, apparently.",
  "this is less of a codebase and more of a cry for help.",
  "commenting your code is a kindness you clearly don't believe in.",
  "the cyclomatic complexity of this function could induce migraines.",
  "this looks like it was generated by an ai that was having a bad day.",
  "sql injection is not a feature, despite what this code suggests.",
  "your try-catch is doing less work than the intern.",
  "this is technically a distributed system — the logic is scattered everywhere.",
  "i asked for clean code. you delivered a crime scene.",
  "this function has more side effects than a clinical trial.",
  "the only abstraction here is an abstraction of good judgment.",
  "your dependency on globals suggests a deep distrust of parameters.",
  "every line of this is valid syntax. that's where the positives end.",
  "this code will work perfectly until it doesn't, and then it'll be spectacular.",
  "you've rediscovered every anti-pattern in the book, and some that aren't.",
  "i've seen more readable code on ancient papyrus.",
  "the architect of this function clearly moonlights as a maze designer.",
  "this is either genius or madness. it's madness.",
  "running this in production would be an act of aggression.",
  "if technical debt had a physical form, this file would be it.",
];

const ISSUE_POOL: Array<{
  severity: Severity;
  badgeLabel: string;
  title: string;
  description: string;
}> = [
  // critical
  {
    severity: "critical",
    badgeLabel: "SECURITY RISK",
    title: "eval() com input do usuário",
    description:
      "Executa código arbitrário fornecido pelo usuário. Vulnerabilidade crítica de RCE — qualquer string pode virar código.",
  },
  {
    severity: "critical",
    badgeLabel: "SQL INJECTION",
    title: "Query construída por concatenação",
    description:
      "Concatenar input diretamente na query permite injeção de SQL. Use prepared statements ou um query builder.",
  },
  {
    severity: "critical",
    badgeLabel: "XSS",
    title: "innerHTML com dados externos",
    description:
      "Escrever HTML diretamente via innerHTML sem sanitização abre vetor para XSS. Use textContent ou sanitize antes.",
  },
  {
    severity: "critical",
    badgeLabel: "CREDENTIALS",
    title: "Credenciais hardcoded no código",
    description:
      "Senhas e tokens no código-fonte acabam em repositórios públicos. Use variáveis de ambiente.",
  },
  {
    severity: "critical",
    badgeLabel: "MEMORY LEAK",
    title: "Event listeners nunca removidos",
    description:
      "Listeners adicionados em loops ou re-renders sem cleanup causam vazamento de memória progressivo.",
  },
  {
    severity: "critical",
    badgeLabel: "RACE CONDITION",
    title: "Estado compartilhado sem sincronização",
    description:
      "Múltiplas operações assíncronas modificando o mesmo estado sem lock ou atomic update geram resultados imprevisíveis.",
  },
  {
    severity: "critical",
    badgeLabel: "NULL DEREF",
    title: "Acesso sem verificação de null",
    description:
      "Acessar propriedades de um valor que pode ser null/undefined vai lançar TypeError em runtime.",
  },
  {
    severity: "critical",
    badgeLabel: "INFINITE LOOP",
    title: "Condição de saída nunca satisfeita",
    description:
      "O loop depende de uma variável que nunca muda dentro do bloco. CPU vai a 100% até o processo ser morto.",
  },
  {
    severity: "critical",
    badgeLabel: "PATH TRAVERSAL",
    title: "Caminho de arquivo construído com input",
    description:
      "Usar input do usuário para montar caminhos de arquivo permite acesso a diretórios arbitrários do servidor.",
  },
  {
    severity: "critical",
    badgeLabel: "NO AUTH",
    title: "Endpoint exposto sem autenticação",
    description:
      "Rota que realiza operações sensíveis não verifica identidade do chamador. Aberto para qualquer requisição.",
  },
  // warning
  {
    severity: "warning",
    badgeLabel: "MAGIC NUMBER",
    title: "Números mágicos sem nomeação",
    description:
      "Literais numéricos espalhados pelo código sem contexto. Extraia para constantes nomeadas com significado semântico.",
  },
  {
    severity: "warning",
    badgeLabel: "GOD FUNCTION",
    title: "Função com responsabilidades demais",
    description:
      "Esta função faz parsing, validação, persistência e resposta HTTP. Cada responsabilidade deve ser sua própria unidade.",
  },
  {
    severity: "warning",
    badgeLabel: "DEEP NESTING",
    title: "Aninhamento excessivo de condicionais",
    description:
      "Quatro níveis de if-else criam fluxo difícil de seguir. Considere early returns ou extração de funções.",
  },
  {
    severity: "warning",
    badgeLabel: "DEAD CODE",
    title: "Código comentado e nunca removido",
    description:
      "Blocos inteiros comentados poluem o arquivo. Para isso existe o histórico do git — delete sem culpa.",
  },
  {
    severity: "warning",
    badgeLabel: "GLOBALS",
    title: "Estado global mutável",
    description:
      "Variáveis globais compartilhadas por múltiplos módulos tornam o fluxo de dados impossível de rastrear.",
  },
  {
    severity: "warning",
    badgeLabel: "NO ERROR HANDLING",
    title: "Promise sem .catch() ou try-catch",
    description:
      "Rejeições não tratadas viram erros silenciosos ou crashes. Sempre trate o caminho de erro explicitamente.",
  },
  {
    severity: "warning",
    badgeLabel: "TYPE COERCION",
    title: "Comparação com == ao invés de ===",
    description:
      "Igualdade fraca causa coerções implícitas que produzem resultados contraintuitivos. Use === sempre.",
  },
  {
    severity: "warning",
    badgeLabel: "COPY-PASTE",
    title: "Lógica duplicada em múltiplos lugares",
    description:
      "O mesmo bloco de código aparece três vezes com pequenas variações. Abstraia numa função parametrizada.",
  },
  {
    severity: "warning",
    badgeLabel: "N+1 QUERY",
    title: "Query dentro de loop",
    description:
      "Uma query executada por iteração causa N+1 chamadas ao banco. Use JOIN ou busque todos os IDs de uma vez.",
  },
  {
    severity: "warning",
    badgeLabel: "POOR NAMING",
    title: "Nomes de variável sem semântica",
    description:
      "Variáveis chamadas 'x', 'temp', 'data2' não comunicam intenção. Nome é documentação — use-o.",
  },
  {
    severity: "warning",
    badgeLabel: "SIDE EFFECTS",
    title: "Função pura com efeitos colaterais ocultos",
    description:
      "A função modifica estado externo sem isso ser óbvio pela assinatura. Efeitos colaterais devem ser explícitos.",
  },
  {
    severity: "warning",
    badgeLabel: "NO PAGINATION",
    title: "SELECT * sem LIMIT em tabela crescente",
    description:
      "Buscar todos os registros sem paginação vai degradar com o tempo. Implemente cursor ou offset+limit.",
  },
  // good
  {
    severity: "good",
    badgeLabel: "GOOD STRUCTURE",
    title: "Separação de responsabilidades presente",
    description:
      "A lógica de negócio está isolada da camada de apresentação. Boa base — só precisa de consistência.",
  },
  {
    severity: "good",
    badgeLabel: "TYPED",
    title: "Tipos explícitos nas interfaces públicas",
    description:
      "As funções exportadas têm assinaturas tipadas. Facilita consumo e reduz erros em integração.",
  },
  {
    severity: "good",
    badgeLabel: "CONSTANTS",
    title: "Algumas constantes nomeadas corretamente",
    description:
      "Parte dos valores literais foi extraída para constantes com nome descritivo. Faça isso em todo o arquivo.",
  },
  {
    severity: "good",
    badgeLabel: "EARLY RETURN",
    title: "Guard clauses utilizados corretamente",
    description:
      "O padrão de retorno antecipado está sendo usado em alguns lugares, evitando aninhamento desnecessário.",
  },
];

// ---------------------------------------------------------------------------
// Code snippet pool (language-specific)
// ---------------------------------------------------------------------------

const CODE_SNIPPETS: Record<string, string[]> = {
  javascript: [
    `eval(prompt("enter code to run"))
document.write(result)
// works on my machine`,
    `var x = 1
var x = 2
var x = "three"
console.log(x * 2) // definitely fine`,
    `function doEverything(data) {
  // parse
  var parsed = JSON.parse(data)
  // validate
  if (parsed) {
    // save to db
    db.query("INSERT INTO users VALUES ('" + parsed.name + "')")
    // send email
    sendEmail(parsed.email)
    // update cache
    cache[parsed.id] = parsed
    // return
    return true
  }
}`,
    `for (var i = 0; i < arr.length; i++) {
  for (var j = 0; j < arr.length; j++) {
    for (var k = 0; k < arr.length; k++) {
      if (arr[i] == arr[j] && arr[j] == arr[k]) {
        result.push(arr[i])
      }
    }
  }
}`,
    `const password = "admin123"
const apiKey = "sk-prod-abc123xyz"
const dbUrl = "postgres://root:root@prod-db:5432/users"
module.exports = { password, apiKey, dbUrl }`,
  ],
  typescript: [
    `function getUser(id) {
  const user = users.find(u => u.id == id)
  return user.profile.name.toUpperCase()
}`,
    `async function fetchAll() {
  const ids = await db.query("SELECT id FROM posts")
  for (const id of ids) {
    const post = await db.query("SELECT * FROM posts WHERE id = " + id)
    results.push(post)
  }
}`,
    `let data: any = fetchData()
let result: any = process(data)
let output: any = format(result)
// typed!
export default output as any`,
    `// TODO: fix this later
// TODO: add validation
// TODO: handle errors
// TODO: write tests
// TODO: remove hardcoded values
const x = 42`,
    `if (user != null) {
  if (user.profile != null) {
    if (user.profile.address != null) {
      if (user.profile.address.city != null) {
        return user.profile.address.city
      }
    }
  }
}`,
  ],
  python: [
    `import os
def run_command(user_input):
    os.system("ls " + user_input)
    # totally safe`,
    `password = "supersecret123"
db_host = "prod.internal.company.com"
admin_token = "Bearer eyJhbGci..."

def connect():
    return psycopg2.connect(db_host, password=password)`,
    `def process(data):
    try:
        result = do_thing(data)
    except:
        pass
    return result`,
    `x = []
for i in range(len(data)):
    for j in range(len(data)):
        x.append(data[i] + data[j])
# O(n²) and proud of it`,
    `def f(x, y, z, a, b, c, d, e):
    if x:
        if y:
            if z:
                return a + b
            else:
                return c - d
        else:
            return e
    return 0`,
  ],
  php: [
    `$query = "SELECT * FROM users WHERE id = " . $_GET['id'];
$result = mysql_query($query);
// input sanitization is for the weak`,
    `<?php
$pass = "admin";
if ($_POST['password'] == $pass) {
    $_SESSION['admin'] = true;
}`,
    `$data = $_POST['data'];
eval($data);
// user knows best`,
    `for ($i = 0; $i < count($items); $i++) {
    $result = mysql_query("SELECT * FROM products WHERE id = " . $items[$i]);
    $products[] = mysql_fetch_array($result);
}`,
    `function doStuff($a,$b,$c,$d,$e,$f) {
$x=0;$y=0;$z=0;
if($a>0){$x=$a*$b;}
if($c!=$d){$y=$c+$d;}
$z=$x+$y+$e+$f;
return $z;
}`,
  ],
  sql: [
    `SELECT * FROM users WHERE 1=1
-- TODO: add authentication
-- TODO: add WHERE clause
-- TODO: add LIMIT`,
    `SELECT u.*, o.*, p.*, a.*, c.*
FROM users u, orders o, products p, addresses a, categories c
WHERE u.id = o.user_id`,
    `DELETE FROM users
-- WHERE id = 123
-- forgot to uncomment`,
    `UPDATE accounts SET balance = balance - 100
-- WHERE account_id = ?
-- will fix in prod`,
    `SELECT * FROM logs
ORDER BY created_at DESC
-- no LIMIT on a table with 50M rows`,
  ],
  java: [
    `public String buildQuery(String name) {
    return "SELECT * FROM users WHERE name = '" + name + "'";
}`,
    `try {
    doSomethingRisky();
} catch (Exception e) {
    // it's fine
}`,
    `public static int counter = 0;
public static String currentUser = null;
public static List<Object> globalState = new ArrayList<>();`,
    `public void processAll(List<Item> items) {
    for (Item item : items) {
        database.save(item);
        emailService.notify(item.getOwner());
        cache.invalidate(item.getId());
        logger.info("processed: " + item);
        analytics.track(item);
    }
}`,
    `if (a != null) {
  if (b != null) {
    if (c != null) {
      if (d != null) {
        return a.get(b).find(c).resolve(d);
      }
    }
  }
}`,
  ],
  go: [
    `func getUser(id string) User {
    row := db.QueryRow("SELECT * FROM users WHERE id = " + id)
    // sql injection as a service
}`,
    `result, _ := doThing()
value, _ := process(result)
output, _ := format(value)
return output`,
    `var globalCache = map[string]interface{}{}
var globalDB *sql.DB
var globalConfig Config`,
    `for _, item := range items {
    go func() {
        shared = append(shared, item) // data race
    }()
}`,
    `func init() {
    init2()
}
func init2() {
    init3()
}
func init3() {
    init()
}`,
  ],
  ruby: [
    `User.where("name = '#{params[:name]}'")
# rails magic (the bad kind)`,
    `eval(params[:code])
# user-generated code execution is fine`,
    `def method_missing(name, *args)
  send(name, *args)
end`,
    `result = nil
begin
  result = risky_operation()
rescue
  # shh
end
result.upcase`,
    `10.times do
  100.times do
    User.find(rand(1000)).update(active: true)
  end
end`,
  ],
  bash: [
    `#!/bin/bash
eval "$1"
# convenient!`,
    `rm -rf /$USER_INPUT/
# what could go wrong`,
    `PASSWORD="admin123"
DB_HOST="prod.db.internal"
curl -u admin:$PASSWORD http://$DB_HOST/api`,
    `for file in $(ls); do
  cat $file | grep "error" | awk '{print $1}'
done`,
    `curl http://untrusted-source.com/script.sh | bash
# yolo deployment`,
  ],
};

const DIFF_TEMPLATES: Array<{
  fileName: string;
  lines: Array<{ lineType: DiffLineType; content: string }>;
}> = [
  {
    fileName: "auth.js",
    lines: [
      { lineType: "context", content: "function authenticate(user, pass) {" },
      {
        lineType: "removed",
        content:
          '  const q = "SELECT * FROM users WHERE pass = \'" + pass + "\'"',
      },
      { lineType: "removed", content: "  return db.query(q)[0]" },
      { lineType: "added", content: "  return db.query(" },
      {
        lineType: "added",
        content: '    "SELECT * FROM users WHERE pass = $1"',
      },
      { lineType: "added", content: "    [pass]" },
      { lineType: "added", content: "  )" },
      { lineType: "context", content: "}" },
    ],
  },
  {
    fileName: "utils.js",
    lines: [
      { lineType: "removed", content: "function calc(x, y, z, a, b) {" },
      {
        lineType: "added",
        content:
          "function calculateTotalPrice(subtotal, tax, discount, shipping, tip) {",
      },
      { lineType: "context", content: "  // renamed parameters for clarity" },
      { lineType: "removed", content: "  return x + y + z - a + b" },
      {
        lineType: "added",
        content: "  return subtotal + tax - discount + shipping + tip",
      },
      { lineType: "context", content: "}" },
    ],
  },
  {
    fileName: "api.py",
    lines: [
      { lineType: "removed", content: "def run(cmd):" },
      { lineType: "removed", content: "    os.system(cmd)" },
      { lineType: "added", content: "def run(cmd):" },
      { lineType: "added", content: "    allowed = ['ls', 'pwd', 'whoami']" },
      { lineType: "added", content: "    if cmd not in allowed:" },
      {
        lineType: "added",
        content: "        raise ValueError('Command not allowed')",
      },
      { lineType: "added", content: "    subprocess.run([cmd], check=True)" },
    ],
  },
  {
    fileName: "queries.ts",
    lines: [
      {
        lineType: "context",
        content: "async function loadPosts(userIds: string[]) {",
      },
      { lineType: "removed", content: "  const posts = []" },
      { lineType: "removed", content: "  for (const id of userIds) {" },
      { lineType: "removed", content: "    posts.push(await db.findPost(id))" },
      { lineType: "removed", content: "  }" },
      { lineType: "added", content: "  const posts = await db.findPosts({" },
      { lineType: "added", content: "    where: { userId: { in: userIds } }," },
      { lineType: "added", content: "  })" },
      { lineType: "context", content: "  return posts" },
      { lineType: "context", content: "}" },
    ],
  },
  {
    fileName: "handler.go",
    lines: [
      { lineType: "removed", content: "result, _ := processRequest(r)" },
      { lineType: "removed", content: "data, _ := serialize(result)" },
      { lineType: "added", content: "result, err := processRequest(r)" },
      { lineType: "added", content: "if err != nil {" },
      { lineType: "added", content: "    http.Error(w, err.Error(), 500)" },
      { lineType: "added", content: "    return" },
      { lineType: "added", content: "}" },
      { lineType: "added", content: "data, err := serialize(result)" },
      { lineType: "added", content: "if err != nil {" },
      { lineType: "added", content: "    http.Error(w, err.Error(), 500)" },
      { lineType: "added", content: "    return" },
      { lineType: "added", content: "}" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function pickVerdict(score: number): Verdict {
  if (score <= 2.0) return "legendary_garbage";
  if (score <= 4.0) return "needs_serious_help";
  if (score <= 6.0) return "could_be_worse";
  if (score <= 8.0) return "not_terrible";
  return "almost_decent";
}

function pickScore(): string {
  // weighted toward low scores (this IS a shame leaderboard)
  const weights = [
    { max: 2.0, weight: 30 },
    { max: 4.0, weight: 35 },
    { max: 6.0, weight: 20 },
    { max: 8.0, weight: 10 },
    { max: 10.0, weight: 5 },
  ];
  const total = weights.reduce((s, w) => s + w.weight, 0);
  let rand = faker.number.int({ min: 1, max: total });
  let min = 0;
  for (const { max, weight } of weights) {
    rand -= weight;
    if (rand <= 0) {
      const val = faker.number.float({ min, max, fractionDigits: 1 });
      return val.toFixed(1);
    }
    min = max;
  }
  return "5.0";
}

function pickIssues(count: number) {
  const shuffled = faker.helpers.shuffle([...ISSUE_POOL]);
  return shuffled.slice(0, count);
}

function pickCodeSnippet(lang: string): string {
  const snippets = CODE_SNIPPETS[lang] ?? CODE_SNIPPETS.javascript;
  return faker.helpers.arrayElement(snippets);
}

// ---------------------------------------------------------------------------
// Main seed
// ---------------------------------------------------------------------------

async function seed() {
  const pool = new Pool({ connectionString: process.env.DATABASE_URL });
  const db = drizzle(pool, { casing: "snake_case" });

  console.log("🌱 Seeding database...\n");

  // clear existing data (order matters due to FKs)
  console.log("  Clearing existing data...");
  await db.delete(roastDiffs);
  await db.delete(roastIssues);
  await db.delete(submissions);

  const TOTAL = 50;

  for (let i = 0; i < TOTAL; i++) {
    const lang = faker.helpers.arrayElement(LANGUAGES);
    const code = pickCodeSnippet(lang);
    const lineCount = code.split("\n").length;
    const scoreStr = pickScore();
    const score = parseFloat(scoreStr);
    const verdict = pickVerdict(score);
    const shameScore = (
      (10 - score) *
      faker.number.float({ min: 0.8, max: 1.2, fractionDigits: 2 })
    ).toFixed(2);
    const roastMode = faker.datatype.boolean({ probability: 0.4 });
    const isPublic = faker.datatype.boolean({ probability: 0.9 });
    const roastQuote = faker.helpers.arrayElement(ROAST_QUOTES);
    const createdAt = faker.date.between({
      from: new Date("2025-01-01"),
      to: new Date(),
    });

    // insert submission
    const [sub] = await db
      .insert(submissions)
      .values({
        code,
        language: lang,
        lineCount,
        roastMode,
        score: scoreStr,
        verdict,
        roastQuote,
        isPublic,
        shameScore,
        createdAt,
      })
      .returning({ id: submissions.id });

    // insert issues (2–4 per submission)
    const issueCount = faker.number.int({ min: 2, max: 4 });
    const picked = pickIssues(issueCount);
    await db.insert(roastIssues).values(
      picked.map((issue, idx) => ({
        submissionId: sub.id,
        severity: issue.severity,
        badgeLabel: issue.badgeLabel,
        title: issue.title,
        description: issue.description,
        sortOrder: idx,
      })),
    );

    // insert diff
    const diff = faker.helpers.arrayElement(DIFF_TEMPLATES);
    await db.insert(roastDiffs).values(
      diff.lines.map((line, idx) => ({
        submissionId: sub.id,
        lineType: line.lineType,
        content: line.content,
        lineNumber: idx + 1,
        sortOrder: idx,
        fileName: diff.fileName,
      })),
    );

    const progress = `[${String(i + 1).padStart(2, " ")}/${TOTAL}]`;
    console.log(
      `  ${progress} ${lang.padEnd(12)} score: ${scoreStr.padStart(4)}  verdict: ${verdict}`,
    );
  }

  await pool.end();

  console.log("\n✅ Seed complete.");
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
